### ISSUE TITLE
is the implemetation working ?

### ISSUE THREAD

**Issue by jojo05** [flyingpot/pytorch_deephash#1]
Did you reproduce the results of the 2015 paper ?
thanks

**Comment by spoonnotfound** [comment]
My result is more than 94% mAP, though the paper result is 89%. Maybe for the reason of different framework or hyperparameters.

**Comment by jojo05** [comment]
wow! Can you provide a trained model ?

**Comment by spoonnotfound** [comment]
The training is much faster and easier than caffe implementation. You can train one yourself. For now I don't have a trained model myself.

**Comment by jojo05** [comment]
ok. Maybe you could update readme and provide quick notes on where to get dataset to train.
Also, can I train on CPU ? How long does it take ?

**Comment by spoonnotfound** [comment]
Yes, I'll update readme in a day or two. My code doesn't support CPU, but you can add the support yourself. If I have time, I'll complete it. It will take me about 2 hours in Titan X(Pascal) to train 200 epochs.

**Comment by jojo05** [comment]
Thanks, look forward to your update. This will help me learn pytorch, thanks

**Comment by spoonnotfound** [comment]
CIFAR10 dataset I used can be downloaded automatically by torchvision.dataset. And torchvision doesn't provide NUS-WIDE dataset, so I haven't implemented the code on NUS-WIDE.

**Comment by jojo05** [comment]
ok, thanks
