### ISSUE TITLE
from coarse to fine searching

### ISSUE THREAD

**Issue by cxy0616** [flyingpot/pytorch_deephash#17]
Thank you very much for the code, but did you implement the search process from coarse to fine when searching? I didn't see it specifically in the code, I would like to trouble you to help me solve this problem!

**Comment by spoonnotfound** [comment]
I don't really know what the 'search process from coarse to fine' is. Can you provide more information?

**Comment by cxy0616** [comment]
As mentioned in the paper, first use the hash code to generate the candidate value, and then use the high-dimensional 4096-dimensional vector for fine-grained retrieval. Recently, I am researching related issues. Can I add qq communication? I look forward to improving together! qq:1054302791

**Comment by cxy0616** [comment]
As mentioned in the paper, first use the hash code to generate the candidate value, and then use the high-dimensional 4096-dimensional vector for fine-grained retrieval. Recently, I am researching related issues. Didn't you see the implementation of the code in this block? thank you for your help!

**Comment by spoonnotfound** [comment]
I didn't implement that. Because I think this may not be very useful to solve this problem. You can implement it by yourself by changing the evalution way.
