### ISSUE TITLE
Hello, Why is the performance of the latest methods on cifar10 not as good as that of 2015? Would you please take a look at this?

### ISSUE THREAD

**Issue by chen-hello** [flyingpot/pytorch_deephash#18]
Hello, Why is the performance of the latest methods on cifar10 not as good as that of 2015? Would you please take a look at this? Is it due to different evaluation criteria? 

https://github.com/swuxyj/DeepHash-pytorch

**Comment by chen-hello** [comment]
Do you know anything better than this method

**Comment by spoonnotfound** [comment]
Sorry for the late reply. I think the reason is the model makes a good use of the pretrained network. And the classification training task can make the network well trained. But I'm not very sure about this since I'm not in this field for a long time. Maybe you can contact the author.
