### ISSUE TITLE
Why the value of mAP in the mAP.py is not change?

### ISSUE THREAD

**Issue by Lin-plax** [flyingpot/pytorch_deephash#19]
Thanks for your working! 
I have run the train.py as the Readme.md. However, when I change the model's pretrained mode the value of mAP is not change, and it's always be 0.9445986000121745. I want to do some change job on your work, thanks again!

**Comment by spoonnotfound** [comment]
I think it's because you didn't use pretrained flag when evaluating. After train, there will be a model in model directory. You need to do evaluation like this.
```
python evaluate.py --pretrained 87(the file name in model directory)
```

**Comment by Lin-plax** [comment]
> I think it's because you didn't use pretrained flag when evaluating. After train, there will be a model in model directory. You need to do evaluation like this.
> 
> ```
> python evaluate.py --pretrained 87(the file name in model directory)
> ```

Thanks for your reply, it works. Thanks for help:)
