### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by josianerodrigues** [flyingpot/pytorch_deephash#2]
Hi @flyingpot,

Thank you for shared with us your project. I would like to use your implementation with a net that I developed myself in place of AlexNet. In that case I would have to modify the net.py file to get the features of my model, but I'm having difficulty. Could you help me?

**Comment by spoonnotfound** [comment]
Yes, you can just show me your problem. Or you can read the docs of [torch.nn.Module](http://pytorch.org/docs/stable/nn.html#torch.nn.Module) to get what you want to know.

**Comment by josianerodrigues** [comment]
Thank you for reply.

The network that I want to use has this architecture:

```
class ResidualNetwork(nn.Module):
    # for input size 32
    def __init__(self):
        super(ResidualAttentionModel_92_32input, self).__init__()
        self.conv1 = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=5, stride=1, padding=2, bias=False),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True)
        )  # 32*32
        self.mpool1 = nn.MaxPool2d(kernel_size=2, stride=2, padding=0)  # 16*16
        self.residual_block1 = ResidualBlock(32, 128)  # 16*16
        self.attention_module1 = AttentionModule_stage1_cifar(128, 128)  # 16*16
        self.residual_block2 = ResidualBlock(128, 256, 2)  # 8*8
        self.attention_module2 = AttentionModule_stage2_cifar(256, 256)  # 8*8
        self.attention_module2_2 = AttentionModule_stage2_cifar(256, 256)  # 8*8 # tbq add
        self.residual_block3 = ResidualBlock(256, 512, 2)  # 4*4
        self.attention_module3 = AttentionModule_stage3_cifar(512, 512)  # 4*4
        self.attention_module3_2 = AttentionModule_stage3_cifar(512, 512)  # 4*4 # tbq add
        self.attention_module3_3 = AttentionModule_stage3_cifar(512, 512)  # 4*4 # tbq add
        self.residual_block4 = ResidualBlock(512, 1024)  # 4*4
        self.residual_block5 = ResidualBlock(1024, 1024)  # 4*4
        self.residual_block6 = ResidualBlock(1024, 1024)  # 4*4
        self.mpool2 = nn.Sequential(
            nn.BatchNorm2d(1024),
            nn.ReLU(inplace=True),
            nn.AvgPool2d(kernel_size=4, stride=1)
        )
        self.fc = nn.Linear(1024,10)

    def forward(self, x):
        out = self.conv1(x)
        out = self.mpool1(out)
        # print(out.data)
        out = self.residual_block1(out)
        out = self.attention_module1(out)
        out = self.residual_block2(out)
        out = self.attention_module2(out)
        out = self.attention_module2_2(out)
        out = self.residual_block3(out)
        # print(out.data)
        out = self.attention_module3(out)
        out = self.attention_module3_2(out)
        out = self.attention_module3_3(out)
        out = self.residual_block4(out)
        out = self.residual_block5(out)
        out = self.residual_block6(out)
        out = self.mpool2(out)
        out = out.view(out.size(0), -1)
        out = self.fc(out)

        return out
```

## I don't know how the latent layer should work in this case.

**Comment by spoonnotfound** [comment]
You should add the latent layer before the last fc.
```python
...
self.latent = nn.Linear(1024, 48)
self.sigmoid = nn.Sigmoid()
self.fc = nn.Linear(48, 10)
...
features = self.sigmoid(self.latent(out))
out = self.fc(features)
return features, out
```

**Comment by josianerodrigues** [comment]
Thank you, @flyingpot.

I changed the net.py file according to your suggestion and tried to train, but get this error:

`RuntimeError: Given groups=1, weight[128, 32, 1, 1], so expected input[128, 128, 32, 32] to have 32 channels, but got 128 channels instead.`

The network was pre-trained for input size 32, with the same structure shown above, I don't understand why it gave this error. Do you have any idea?

Sorry for taking your time and thank you for help me.

**Comment by spoonnotfound** [comment]
Can you give me a more detailed error? I need to know where the error happens in your code. 
The required input size is 32\*32. In my code, the input size is 227\*227, and you should edit the preprocessing code. For example:
```python
transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop((32, 32), padding=4),
    transforms.ToTensor()
])
```

**Comment by josianerodrigues** [comment]
I put exactly the same preprocessing.

```
transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop((32, 32), padding=4),
    transforms.ToTensor()
])
```
The error happens when the code line `out = self.residual_block1(out) ` is called.
```
  File "train.py", line 144, in <module>
    val_loss = train(epoch)
  File "train.py", line 93, in train
    _, outputs = net(inputs)
  File "/home/josiane/anaconda3/envs/baselines/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/josiane/Baselines/Hashing-Residual-Attention-Network/net.py", line 41, in forward
    out = self.residual_block1(out)
  File "/home/josiane/anaconda3/envs/baselines/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/josiane/anaconda3/envs/baselines/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/josiane/anaconda3/envs/baselines/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/josiane/anaconda3/envs/baselines/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/josiane/anaconda3/envs/baselines/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: Given groups=1, weight[128, 32, 1, 1], so expected input[128, 128, 32, 32] to have 32 channels, but got 128 channels instead
```

**Comment by josianerodrigues** [comment]
Hi @flyingpot,
Could you answer a question? How would the list of the network parameters look?
I put it that way:

`base_params = list(net.conv1.parameters()) + list(net.residual_block1.parameters()) + list(net.attention_module1.parameters()) + list(net.residual_block2.parameters()) + list(net.attention_module2.parameters()) + list(net.attention_module2_2.parameters()) + list(net.residual_block3.parameters()) + list(net.attention_module3.parameters()) + list(net.attention_module3_2.parameters()) + list(net.attention_module3_3.parameters()) + list(net.residual_block4.parameters()) + list(net.residual_block5.parameters()) + list(net.residual_block6.parameters()) + list(net.mpool2.parameters())`

Is correct?

**Comment by spoonnotfound** [comment]
@josianerodrigues My codes about base_params is not necessary. I'll edit it soon. Just delete it, and keep the learning rate the same for all parameters.

**Comment by spoonnotfound** [comment]
I can't find the error. Maybe you can print out the size of data and check if it is correct.

**Comment by josianerodrigues** [comment]
Thank you :)

**Comment by josianerodrigues** [comment]
Hi @flyingpot,

The MAP that you calculated was for top 1 precision.

**Comment by spoonnotfound** [comment]
I'm quite sure it is mean Average Precision. I write the code following the matlab code of the author.

**Comment by josianerodrigues** [comment]
Thank you again :)

**Comment by josianerodrigues** [comment]
How to calculate the hamming and euclidian distance in file mAP.py? I think the distance is calculate in this line:

`query_result = np.count_nonzero(query_binary != trn_binary, axis=1)`

Am I right?

Sorry for taking your time.

**Comment by spoonnotfound** [comment]
Yes, it is the code calculating hamming distance.
