### ISSUE TITLE
hello~这是什么语法

### ISSUE THREAD

**Issue by kevinxu-cn97** [flyingpot/pytorch_deephash#20]
inner_product = hi @ hj.t()

**Comment by spoonnotfound** [comment]
[矩阵相乘](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)

**Comment by kevinxu-cn97** [comment]
使用DCH，需要自己对图像数据编程进行onehot编码吗？datasets需要怎么操作捏。

**Comment by spoonnotfound** [comment]
不了解这个
