### ISSUE TITLE
mAP is zero,see the log below

### ISSUE THREAD

**Issue by mxq-151** [flyingpot/pytorch_deephash#3]
('Query ', 9981)
('Query ', 9982)
('Query ', 9983)
('Query ', 9984)
('Query ', 9985)
('Query ', 9986)
('Query ', 9987)
('Query ', 9988)
('Query ', 9989)
('Query ', 9990)
('Query ', 9991)
('Query ', 9992)
('Query ', 9993)
('Query ', 9994)
('Query ', 9995)
('Query ', 9996)
('Query ', 9997)
('Query ', 9998)
('Query ', 9999)
('Query ', 10000)
0.0
('total query time = ', 98.12934589385986)

pytorch's version is 0.3.1 and torchvision is 0.2
that's master about pytorch's version?
call you do me a favour? thx
@flyingpot

**Comment by spoonnotfound** [comment]
Maybe this is the version's problem. Because even when you randomly initialize a model, the mAP should not be zero.

**Comment by mxq-151** [comment]
change pytorch version to 0.2.0,it still get zero result . for more detail,the python version is 2.7.14

**Comment by spoonnotfound** [comment]
You should try Python 3.6. I forgot to put Python version in the doc.

**Comment by mxq-151** [comment]
yeah,I try python 3.6,it works,thanks a lot
