### ISSUE TITLE
训练集大于10类时，训练报错

### ISSUE THREAD

**Issue by fanxuansoft** [flyingpot/pytorch_deephash#9]
您好，借用您的代码，用自己的图片进行训练时：
trainset = datasets.ImageFolder(root='data/out', transform=transform_train)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=128,
                                          shuffle=True, num_workers=2)

如果'data/out下的分类大于10时，程序就会报错：
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/Threshold.cu:67

您知道是什么原因吗？

**Comment by spoonnotfound** [comment]
你有没有修改net.py文件里的输出节点数呢？

**Comment by fanxuansoft** [comment]
谢谢！我没有注意到这一点！！！
